		PUBLIC SIRALIMI
		EXTRN dizi:BYTE, n:WORD
mycs2	SEGMENT PARA 'kod2'
		ASSUME CS:mycs2
SIRALIMI	PROC FAR
		PUSH CX
		PUSH SI
		MOV CX, n
		MOV AL, 1
		DEC CX
		XOR SI, SI
don:	CMP SI, CX
		JAE SIRALI 
		MOV AH, dizi[SI]
		CMP AH, dizi[SI+1]
		JGE SIRASIZ
		INC SI
		JMP don
SIRASIZ: MOV AL, 0	
SIRALI:	POP SI
		POP CX
		RETF
SIRALIMI ENDP
mycs2	ENDS
		END