/*
word tanýmlý,pozitif sayilardan olusan,10 elemanlý bir dizinin en büyük elemaný
BUYUK isimli harici bir yordam yardýmýyla bulan programý ve söz konusu harici yordamýn içinde yer alacagý yardýmcý programý yazalým.

örnegimizde yazmamýz beklenen iki programdan ilki,10 elemanlý dizinin tanýmlandýgý ve genel olarak kontrolu elinde bulunduracak olan örnek 11-1 ASM isimli program,ikincisi ise BUYUK isimli yordamý bulunduracak olan ÖRNEK 11-1-1 ASM isimli programdýr.
BUYUK isimli yordamýn FAR olarak tanýmlandýgýný kabul ederek ilk programýmýzý kodlayacak olursak

*/

//PROGRAM:ÖRNEK 11-1.ASM
//KULLANILACAK HARÝCÝ BÝR YORDAM ÝLE DÝZÝ ÝÇÝNDEKÝ EN BUYUK ELEMANI BULMA.
//KOD KESÝMLERÝ BÝRLEÞTÝRÝLÝÞTÝR.

PAGE 60,80
TITLE CODE KESÝMLERÝ BÝRLEÞÝK -YARDIMCI YORDAM ÇAÐIRMA

//BUYUK HARÝCÝ BÝR YORDAMDIR.FAR OLARAK TANIMLANMIÞTIR.
//DIZI ÝSE BASKA BÝR PROGRAM TARAFINDAN KULLANILACAKTIR.

EXTRN BUYUK:FAR
PUBLIC DIZI
STSEG SEGMENT PARA STACK 'STACK'
DW 12 DUP(0)
STSEG ENDS
DTSEG SEGMENT PARA 'DATA'

//KULLANILACAK DEGÝSKENLER TANIMLANIR.

DIZI DW 12,1,5,64,21,65,127,512,0,1024
ELEMAN DW 10
BYK_EL DW ?
DTSEG ENDS 
CDSEG SEGMENT PARA PUBLIC 'CODE'	;//KESÝM BÝRLEÞTÝRÝLECEK
	ASSUME CS:CDSEG,SS:STSEG,DS:DTSEG
	BASLA PROC FAR
	

//DONUS ÝÇÝN GEREKLÝ OLAN DEGERLER YIGINDA SAKLANIYOR.

PUSH DS
XOR AX,AX
PUSH AX

//DTSEG ÝSMÝYLE TANIMLI KESÝM ALANINA ERÝÞEBÝLMEK ÝÇÝN GEREKLÝ TANIMLAR

MOV AX,DTSEG
MOV DS,AX

//ÝÞLEM BLOGU BASLIYOR.
MOV CX,ELEMAN	;//ELEMAN SAYISINI CX ÝLE BUYUK ÝSÝMLÝ YORDAMA AKTAR
CALL BUYUK 		;//BUYUK ÝSÝMLÝ YORDAMI ÇAÐIRILIR
MOV BYK_EL,AX	;//EN BUYUK DEGER AX YAZMACI ÜZERÝNDEN GERÝ DONER
RET				;//DOS' DON
BASLA ENDP
CDSEG ENDS
END BASLA		;//PROGRAMIN BASLANGIC NOKTASI	








//PROGRAM 11-1-1.ASM
//ORNEK 11-1.ASM ÝSÝMLÝ PROGRAM TARAFINDAN ÇAÐIRILAN  YARDIMCI YORDAM  KOD KESÝMLERÝ BÝRLESTÝRÝLMÝSTÝR.

PAGE 60,80
TITLE CODE KESÝMLERÝ BÝRLEÞÝK - YARDIMCI YORDAM ÇAÐIRMA

//BUYUK ÝSÝMLÝ YORDAM BASKA PROGRAMLAR TARAFINDAN DA KULLANILABÝLÝR.
//DIZI ÝSE BASKA BÝR KESÝM DE WORD TANIMLI HARÝCÝ VERÝDÝR.

EXTRN DIZI:WORD
PUBLIC BUYUK
CDSEG SEGMENT PARA PUBLIC 'CODE'	;//KESÝM BÝRLEÞTÝRÝLECEK
ASSUME CS:CDSEG
BUYUK PROC FAR

//ÝSLEM BLOGU BASLIYOR.
//CX UZERÝNDEN DÝZÝNÝN ELEMAN SAYISI BU YORDAMA AKTARILIYOR.

XOR SI,SI	;//SI DÝZÝ ÝNDÝSÝ OLARAK KULLANILACAK 
MOV AX,DIZI[SI]	;//ÝLK ELEMANI EN BUYUK KABUL ET
SUB CX,1		;//GERÝ KALAN ELEMANLAR ÜZERÝNDEN ÝÞLEM YAPILACAK 
L1:ADD SI,2		;//DW TANIMLI BÝR SONRAKÝ ELEMAN 2 BYTE ÝLERÝDE 
CMP AX,DIZI[SI]
JA DEVAM
MOV AX,DIZI[SI]	;//DÝZÝNÝN ELEMANI DAHA BUYUK
DEVAM:LOOP L1	;//CEVRÝMÝ TEKRARLA 
RET				;//ÇAÐIRAN NOKTAYA GERÝ DON
BUYUK ENDP
CDSEG ENDS 
END


