/*
örnek 11-2
örnek 11-2 asm isimli programdaki yordam ý_word isimli harici degiskeni,kendi veri kesiminde tanýmlý olan I_byte1 ve I_byte2 isimli byte tanýmlý degiskenlere yerlestirmekte,ardýndan ALTPRG isimli harici bir yordamý(Örnek 11-2-1 ASM isimli program içinde yer alan)çaðýrmaktadýr.
örnek 11-2.ASM ve örnek 11-2-1.ASM isimli programlarýn veri kesimlerini birleþtirmek üzere her iki programýn veri kesimleri de ayný þekilde tanýmlanacaktýr.
veri alanýnda kullanýlamayan bölgenin en aza indirilmesi için kesim hizalama tipi olarak BYTE kullanýlacaktýr.
þimdi bu bilgiler ýþýgýnda örnek 11-2 ASM kodunu yazalým.

*/

//PROGRAM :ÖRNEK 11-2.ASM
//örnek 11-2-1.ASM ile veri kesimleri birleþtirilmiþtir.

PAGE 60,80
TITLE VERÝ KESÝMLERÝ BÝRLEÞÝK

//ALTPRRG VE I_WORD ÖRNEK 11-2-1.ASM ÝÇÝNDE TANIMLIDIR.
//B_WORD ÝSE ÖRNEK 11-2-1.ASM ÝÇÝNDEKÝ ALTPRG ÝSÝMLÝ YORDAM ERÝÞECEKTÝR.

EXTRN ALTPRG:FAR,I_WORD:WORD
PUBLIC B_WORD
STSEG SEGMENT PARA STACK 'STACK'
DW 12 DUP(0)
STSEG ENDS

//VERÝ KESÝMÝ PUBLÝC TANIMLANMIÞTIR.AYRICA BYTE TANIMI ÝLE TUM ALANIN ETKÝN KULLANILMASI AMAÇLANMIÞTIR.

DTSEG SEGMENT BYTE PUBLÝC 'DATA'
I_BYTE1 DB ?
I_BYTE2 DB ?
B_WORD DW 0ABCDH
DTSEG ENDS
CDSEG SEGMENT PARA 'CODE'
ASSUME CS:CDSEG,SS:STSEG,DS:DTSEG
BASLA PROC FAR

//DONUS ÝÇÝN GEREKLÝ OLAN DEGERLER YIGINDA SAKLANIYOR.

PUSH DS
XOR AX,AX
PUSH AX

//DTSEG ÝSMÝYLE TANIMLI VERÝ KESÝMÝNE ERÝÞEBÝLMEK ÝÇÝN GEREKLÝ TANIMLAR

MOV AX,DTSEG
MOV DS,AX

//ÝÞLEM BLOGU BASLIYOR

MOV AX,I_WORD	;//ÖRNEK 11-2-1.ASM ÝÇÝNDEKÝ DEGERÝ AL
MOV I_BYTE1,AL	;//PARCALAYARAK KENDÝ ÝÇÝNDE TANIMLI DEGÝSKENLERE 
MOV I_BYTE2,AH	;//YERLESTÝR.
CALL ALTPRG		;//HARÝCÝ YORDAMI ÇAÐIR.
RET				;//DOS'A DÖN
BASLA ENDP		
CDSEG ENDS
END BASLA		;//PROGRAMIN BASLANGÝC NOKTASI







/*
ÖRNEK 11-2-1.ASM ÝSÝMLÝ PROGRAM ÝSE B_WORD ÝSÝMLÝ HARÝCÝ DEGÝSKENÝ,KENDÝ VERÝ KESÝMÝNDE TANIMLI B_BYTE1 VE B_BYTE2 ÝSÝMLÝ DEGÝSKENLERE YERLEÞTÝREN ALTPRG ÝSÝMLÝ BÝR YORDAMA SAHÝPTÝR.

BU YORDAM,ÖRNEK 11-2.ASM ÝSÝMLÝ PROGRAM TARAFINDAN HARÝCÝ YORDAM OLARAK ÇAÐRILMAKTADIR.
VERÝ KESÝMLERÝNÝN DE BÝRLEÞTÝRÝLECEGÝNÝ DÝKKATE ALARAK ÖRNEK 11-2-1.ASM ÝSÝMLÝ PROGRAMI YAZALIM.


*/

//PROGRAM :ÖRNEK 11-2-1.ASM
//ÖRNEK 11-2.ASM ÝLE VERÝ KESÝMLERÝ BÝRLEÞTÝRÝLÝÞTÝR.

PAGE 60,80
TITLE VERÝ KESÝMLERÝ BÝRLEÞÝK

//ALTPRG VE I_WORD  ÖRNEK 11-2 ASM TARAFINDAN  KULLANILACAKTIR.
//B_WORD,ÖRNEK 11-2.ASM ÝÇÝNDE TANIMLIDIR.

PUBLIC ALTPRG,I_WORD
EXTRN B_WORD:WORD

//VERÝ KESÝMÝ PUBLÝC TANIMLANMIÞTIR.
//AYRICA BYTE TANIMI ÝLE TUM ALANIN ETKÝN KULLANILMASI AMACLANMIÞTIR.

DTSEG SEGMENT BYTE PUBLIC 'DATA'
B_BYTE1 DB ?
B_BYTE2 DB ?
I_WORD DW 01234H
DTSEG ENDS
CODESG SEGMENT PARA 'CODE'
ASSUME CS:CODESG,DS:DTSEG

ALTPRG PROC FAR

//ÝÞLEM BLOGU BASLIYOR.

MOV AX,B_WORD	;//ÖRNEK 11-2.ASM ÝÇÝNDEKÝ B_WORD DEGERÝNÝ AL
MOV B_BYTE1,AL	;//KENDÝ VERÝ KESÝMÝNDE TANIMLI DEGÝSKENLERE KOY
MOV B_BYTE2,AH	
RET				;//ÇAÐIRAN NOKTAYA GERÝ DON
ALTPRG ENDP
CODESG ENDS
END


