/* 
ÖRNEK 10-3
ÖRNEÐÝMÝZ BÝLGÝSAYAR EKRANÝ TEMÝZLEYÝP BÝR MESAJ YAZDIRMAK OLSUN.
PROGRAMIMIZ,DAHA AZ KESÝM TANIMI YAPILMASI VE SADECE YAPISI NEDENÝ ÝLE COM TÝPÝNDE OLUP,EKRANI TEMÝZLEMEK ÜZERE SIL VE MESAJ YAZDIRMAK ÝÇÝN ÝSE YAZDIR ÝSÝMLÝ MAKROLARDAN YARARLANILACAKTIR.

MAKROLARIN EKRANI SÝLMESÝ VE MESAJ YAZDIRABÝLMESÝ ÝÇÝN MEVCUT BIOS/DOS KESME FONKSÝYONLARINDAN INT KOMUTUNU KULLANARAK FAYDALANACAGIZ.
HER NE KADAR SU ANA KADAR OLAN KISIMDA KESME (ÝNTERRUPT) KAVRAMINDAN SÖZ EDÝLMEMÝS DAHÝ OLSA
KESME YORDAMLARI DA ASSEMBLY KOMUTLARINDAN OLUSMUS PROGRAM PARCALARIDIR.

KESME YORDAMLARI YAPTIKLARI ÝÞE GÖRE ÇAÐRILMADAN ÖNCE ÝLGÝLÝ YAZMACLARIN ÝLK DEGERLERÝNÝN UYGUN SEKÝLDE AYARLANMASI ÝLE KULLANILABÝLÝR.
YAPTIKLARI ÝÞÝN NÝTELÝÐÝNE BAÐLI OLARAK DA BÝR SONUC DEGERÝ DONDUREBÝLÝR.

BU ÖZELLÝKLERÝ DÝKKATE ALINDIGINDA ASLINDA KESÝMLER ARASI (ÝNTERSEGMENT)YORDAM ÇAÐIRMAYA COK BENZER ÖZELLÝKTE ÇALIÞIRLAR.

EKRANI SILMEK ÝÇÝN KULLANICAGIMIZ INT 10 H-FONKSÝYON 06H,CX,DX,AH VE BH YAZMACLARINDAN PARAMETRE ALIR.
EKRANA MESAJ YAZDIRMAK ÝÇÝN KULLANILCAK OLAN 21H-FONKSÝYON 09H ÝSE DX VE AH YAZMACLARINDAN PARAMETRE ALMAKTADIR.
BU KESME YORDAMLARINI KULLANACAK OLAN SIL ÝSÝMLÝ MAKRO PARAMETRE ALMAYACAK ANCAK YAZDIR ÝSÝMLÝ MAKRO EKRANA YAZDIRILACAK OLAN MESAJI PARAMETRE OLARAK ALACAKTIR.

*/

//PROGRAM :ÖRNEK 10-3 ASM
//COM YAPISINDAKÝ PROGRAMDA MACRO KULLANIMI 
//PROGRAM EKRANI TEMÝZLEDÝKTEN SONRA BÝR MESAJ YAZACAKTIR.

PAGE 60,80
TITLE EKRANA MESAJ YAZMA
CDSEG SEGMENT PARA 'CODE'
ORG 100H	;//COM PROGRAM 100H DEN BASLAR
ASSUME CS:CDSEG,SS:CDSEG,DS:CDSEG

//INT 10H YARDIMIYLA EKRANI SÝLMEYÝ SAÐLAYAN MACRO KODU

SIL MACRO
MOV CX,0000H	;//EKRANIN SOL ÜST KÖÞESÝ SATIR/SUTUN ADRESÝ
MOV DX,184FH	;//EKRANIN SAÐ ALT KOSESÝ SATIR/SUTUN ADRESÝ
MOV BH,07H		;//ÖZNÝTELÝK DEGERÝ (ATTRIBUTE BYTE)
MOV AX,0600H	;//AH=06H PENCEREYÝ YUKARI KAYDIRMA
INT 10H			;//10H NUMARALI KESMEYÝ ÇAÐIR
ENDM

//INT 21H YARDIMIYLA EKRANA MESAJ YAZDIRAN MACRO

YAZDIR MACRO TEXT
LEA DX,TEXT		;//DX YAZDIRILACAK MESAJIN BASINI GÖSTERMELÝ
MOV AH,09H		;//AH=09H EKRANA MESAJ YAZMA
INT 21H			;//21H NUMARALI KESMEYÝ ÇAÐIR. 
ENDM	

//MACROLARI KULLANARAK ÝÞLEMÝ GERÇEKLEÞTÝREN YORDAM 

BASLA PROC NEAR
SIL				;//SIL ÝSÝMLÝ MACROYU KULLAN 
YAZDIR MESAJ 	;//YAZDIR MAKROSUNU MESAJ PARAMETRESÝ ÝLE KULLAN
RET
BASLA ENDP


//MESAJIN TANIMLANDIGI ALAN
MESAJ DB 'EKRAN SÝLÝNDÝ VE BU MESAJ YAZILDI...','$'
CDSEG ENDS
END BASLA		;//PROGRAMIN BASLANGÝC NOKTASI
