/*
ÖRNEK 10-4
ÖRNEK 10-3'DE YAZDIGIMIZ PROGRAMDA BASÝT BÝR DEGÝSÝKLÝK YAPARAK MAKROLARIN HARÝCÝ BÝR DOSYADAN ALINMASI DURUMUNDA YAPILCAKLARI ÝNCELEYELÝM.

*/

//PROGRAM :ÖRNEK 10-4 ASM
//COM YAPISINDAKÝ PROGRAMDA MACRO KULLANIMI 
//PROGRAM EKRANI TEMÝZLEDÝKTEN SONRA BÝR MESAJ YAZACAKTIR.
//MACRO'LAR HARÝCÝ BÝR DOSYADAN ALINARAK KULLANILACAKTIR.

PAGE 60,80
TITLE EKRANA MESAJ YAZMA

//KULLANILACAK MACRO'LAR ORNEK.MAC ÝSÝMLÝ DOSYADAN ALINMAKTADIR.

INCLUDE ORNEK.MAC
CDSEG SEGMENT PARA 'CODE'
ORG 100H		;//COM PROGRAM 100H DEN BASLAR
ASSUME CS:CDSEG,SS:CDSEG,DS:CDSEG

//MACROLARI KULLANARAK ÝÞLEMÝ GERCEKLESTÝREN YORDAM 

BASLA PROC NEAR
SIL 			;//SIL ÝSÝMLÝ MACRO'YU KULLAN 
YAZDIR MESAJ 	;//YAZDIR MAKROSUNU MESAJ PARAMETRESÝ ÝLE KULLAN 
RET
BASLA ENDP

//MESAJ TANIMI

MESAJ DB 'MACRO'LAR ORNEK.MAC DOSYASINDAN ALINDI','$'
CDSEG ENDS
END BASLA	;PROGRAM



//MAKROLAR PROGRAMIMIZ ÝLE AYNI DÝZÝNDE BULUNAN ORNEK.MAC ÝSÝMLÝ DOSYADA  YER ALMAKTADIR.
//ORNEK.MAC ÝSÝMLÝ DOSYA ASAGIDAKÝ SEKÝLDE YAZILACAKTIR.

//DOSYA:ORNEK.MAC
//BU DOSYA HARÝCÝ MACRO'LARIN YER ALDIGI BÝR DOSYADIR.

//INT 10H YARDIMIYLA EKRAN SÝLMEYÝ SAÐLAYAN MACRO KODU

SIL MACRO
	MOV CX,0000H	;//EKRANIN SOL ÜST KOSESÝ SATIR/SUTUN ADRESÝ
	MOV DX,184FH	;//EKRANIN SAÐ ALT KÖÞESÝ SATIR/SUTUN ADRESÝ
	MOV BH,07H		;//ATTRÝBUTE BYTE
	MOV AX,0600H	;//AH =06 H PENCEREYÝ YUKARI KAYDIR
	INT 10H			;//10H NUMARALI KESMEYÝ ÇAÐIR
	ENDM
	
	//INT 21H YARDIMIYLA EKRANA MESAJ YAZDIRAN MACRO
	
	YAZDIR MACRO,TEXT
	LEA DX,TEXT		;//DX YAZDIRILACAK MESAJIN BASINI GÖSTERMELÝ
	MOV AH,09H		;//AH = 09H EKRANA MESAJ YAZ
	INT 21H			;//21H NUMARALI KESMEYÝ ÇAÐIR
	ENDM
	
	



