/*
32 bit uzunlugunda pozitif iki tam sayi toplayan programi EXE tipinde yazalim

PROGRAM:Örnek 9-2 ASM
32 bit olarak tanýmlanmýþ olan ASAYISI ve BSAYISI isimli degiskenleri toplayarak elde edilen 
sonucu toplam isimli 64 bitlik degiskene yerlestiren EXE tipinde program

*/
PAGE 60,80
TITLE 32 BITLIK POZITIF IKI SAYININ TOPLANMASI

STACKSG SEGMENT PARA STACK 'STACK'
DW 10 DUP(?)
STACKSG ENDS

DATASG SEGMENT PARA 'DATA'
ASAYISI DD 12345678H
BSAYISI DD 9ABCDEF0H
TOPLAM DQ 0H
DATASG ENDS
CODESG SEGMENT PARA 'CODE'
ASSUME CS:CODESG,DS:DATASG,SS:STACKSG
ANA PROC FAR
//DONUS ÝÇÝN GEREKLÝ OLAN DEGERLER YIGINDA SAKLANIYOR
PUSH DS
SUB AX,AX
PUSH AX
//DATASG ÝSMÝYLE TANIMLÝ KESÝM ALANÝNA ERÝSMEK ÝÇÝN GEREKLÝ TANIMLAR
MOV AX,DATASG
MOV DS,AX
//TOPLAMA ÝÞLEMÝNÝN GERÇEKLEÞTÝRÝLDÝGÝ KOD BLOGU
LEA SI,ASAYISI	;//SAYÝLARLA BÝR SEFERDE 64 BÝT TOPLAMA YAPILMADIGI ÝÇÝN 
LEA DI,BSAYISI	;//16 BÝT'LÝK PARCALAR HALÝNDE OKUNACAKTIR
LEA BX,TOPLAM	;//BU NEDENLE SAYÝLARLA SI/DI/BX YAZMACLARI YARDIMIYLA ERÝSÝLECEKTÝR

MOV AX,[SI]		;//AX YAZMACÝNA ASAYÝSÝNÝN DUSUK ANLAMLI WORD'U
MOV DX,[DI]		;//DX YAZMACINA BSAYÝSÝNÝN DUSUK ANLAMLI WORDU
ADD AX,DX
MOV [BX],AX		;//ELDE EDÝLEN TOPLAM'IN DUSUK ANLAMLI WORDUNE
MOV AX,[SI+2]	;//AX YAZMACINA ASAYÝSÝNÝN YUKSEK ANLAMLI WORDU
MOV DX,[DI+2]	;//DX YAZMACINA BSAYISININ YUKSEK ANLAMLI WORDU
ADC AX,DX		;//ELDEYÝ DE ÝÞLEME DAHÝL EDÝYORUZ VE SONUCU 
MOV [BX+2],AX	;//TOPLAM DEGÝSKENÝNE YAZÝYORUZ
ADC WORD PTR [BX+4],0
				;//ÝKÝ SAYÝNÝN 32 BÝT TOPLAMÝNDA ELDE OLUSMUS ÝSE BU DEGERÝ
				;//TOPLAM DEGÝSKENÝNÝN YUKSEK ANLAMLÝ DWORD ALANINA AKTARABÝLMEK ÝÇÝN
				;//ELDELÝ TOPLAMA ÝÞLEMÝ YAPIYORUZ

RET 
ANA ENDP
CODESG ENDS
END ANA 	;//PROGRAMÝN BASLANGÝC NOKTASI
