/*
farklý bir cozum olarak TEST komutunu sayinin tek/cift olmasini belirleyen en az anlamlý bit 
disindakileri 0 yapacak bir maske ile kullanýp ZF bayragýnýn durumuna gore karar verebiliriz
buna gore programimizi tekrar yazarsak

program:ornek 9-3,ASM
10 elemanlý bir dizideki tek ve cift sayilarin adedini bulan program 
bu programda TEST komutu kullanýlmýstýr

*/
PAGE 60,80
TITLE TEK CIFT/TEST KULLANARAK 
SSEG SEGMENT PARA STACK 'STACK'
DW 12 DUP(0)
SSEG ENDS
DSEG SEGMENT PARA 'DATA'
//DEGÝSKEN TANIMLARI
DIZI DW 10,21,43,71,199,67,88,234,0,467
ELEMAN DW 10
TEK_S DW 0
CIFT_S DW 0
DSEG ENDS
CSEG SEGMENT PARA 'CODE'
TC PROC FAR
ASSUME CS:CSEG,SS:SSEG,DS:DSEG

//DONUS ÝÇÝN GEREKLÝ OLAN DEGERLER YIGINDA SAKLANIYOR
PUSH DS
XOR AX,AX
PUSH AX
//DSEG ÝSMÝYLE TANIMLI KESÝM ALANÝNA ERÝSEBÝLMEK ÝÇÝN GEREKLÝ OLAN TANIMLAR
MOV AX,DSEG
MOV DS,AX
//KONTROL ÝÞLEMÝNÝN GERÇEKLESTÝRÝLDÝGÝ KOD BLOGU
	MOV CX,ELEMAN		;//CEVRÝM DEGÝSKENÝNE ELEMAN SAYÝSÝ KONUR
	LEA SI,DIZI			;//DIZI'NIN BASLANGIC ADRESÝ SI YAZMACINDA
	CEVRIM:TEST WORD PTR[SI],0001H	;//TEST KOMUTU ÝÞLENENLERÝ BOZMAZ

	JZ CIFT				;//SONUC SIFIR ÝSE SAYÝ CÝFTTÝR ÝLGÝLÝ SATÝRA GÝT
TEK:INC TEK_S			;//SAYÝ TEKTÝR TEK SAYÝ ADEDÝNÝ ARTTIR
CIFT: ADD SI,2			;//BÝR SONRAKÝ ELEMANA ERÝSMEK ÝÇÝN SI ARTTIRILIR
						;//DIZI WORD TANIMLI OLDUGU ICIN BÝR SONRAKÝ DÝZÝ ELEMANI 2 BYTE ÝLERÝDE OLUCAKTIR
	LOOP CEVRÝM			;//ÝSLEMÝ DÝZÝNÝN SON ELEMANINA GELÝNCEYE KADAR TEKRARLAMAYI SAÐLAYAN CEVRÝM KOMUTU
	
	MOV AX,ELEMAN		;//CEVRÝM SONUCUNDA SADECE TEK OLAN KAC TANE ELEMAN OLDUGUNU BÝLÝYORUZ
	SUB AX,TEK_S		;//ELEMAN SAYÝSÝNDAN ÇIKARTIR BOYLECE KALANLARIN CÝFT OLDUGUNU BULABÝLÝRÝZ 
	MOV CIFT_S,AX		;//BULDUGUMUZ DEGERÝ TANIMLI DEGÝSKENE YAZ
	
	RET
	TC ENDP
	CSEG ENDS
	END TC				;//PROGRAMIN BASLANGIC NOKTASI
