/*
DÝZÝ ELEMANLARI ÜZERÝNDE BÝT ÝÞLEMLERÝ

10 ADET WORD TÝPÝNDE ELEMANI OLAN BÝR DÝZÝ ELEMANLARININ BÝNARY (ÝKÝLÝ SAYÝ SÝSTEMÝNDE)
GÖSTERÝMÝNDE EN COK 1 BARINDIRAN ELEMANIN ADRESÝNÝ BULAN VE BUNU BELLEK ÜZERÝNDEKÝ
BÝR DEGÝSKENDE SAKLAYAN COM TÝPÝ ASSEMBLY PROGRAMINI YAZALIM.

*/

//BÝR SAYININ EN DÜÞÜK ANLAMLI BÝTÝ'NÝN NE OLDUGUNU TESPÝT ETMEK ÝÇÝN AKIÞ DÝYAGRAMINDA GENEL BÝR YAPI TERCÝH EDÝLMÝÞKEN 
//PROGRAM YAZILIRKEN ASSEMBLY KODLARININ KABÝLÝYETLERÝ KULLANILARAK ÖTELEME VE CF ÝLE TOPLAMA ÝÞLEMLERÝ ÝLE DAHA KISA VE EFEKTÝF BÝR PROGRAM YAZILMIÞTIR.


MYCODE SEGMENT PARA 'CODE'
ORG 100H
ASSUME CS:MYCODE,SS:MYCODE,DS:MYCODE
MAIN PROC NEAR
XOR DI,DI

XOR SI,SI
XOR DX,DX
MOV CX,ELEMAN
MOV AX,DIZI[SI]
PUSH CX
MOV CX,16

XOR DL,DL
SHR AX,1

ADC DL,0
LOOP L1
CMP DH,DL
JGE NEXT
MOV DH,DL
MOV DI,SI
NEXT:POP CX
ADD SI,2
LOOP L2
MOV YER,DI
RET
MAIN ENDP
ELEMAN DW 10
DIZI DW 88H,45H,71H,77H,63H,0AAH,56H,12H,92H,0BFH
YER DW ?
MYCODE ENDS
END MAIN


