/*
DÝZÝDE OLMAMASI GEREKEN VERÝYÝ BULMA

15 YAÞINDAN KUCUK VE 50 YASINDAN BUYUK 10 KISININ OLDUGU SIRAYA YAS KOSULUNU
BOZAN 11.KISI KARISMISTIR.SIRADAKÝ TUM KISILERIN (11 KÝSÝNÝN)YASLARI BÝLÝNDÝGÝNE GÖRE,SIRAYA SONRADAN KARISAN KÝSÝNÝN BASTAN KACINCI SIRADA OLDUGUNU BULAN COM TÝPÝ ASSEMBLY PROGRAMINI YAZINIZ.


*/

//COM TÝPÝ PROGRAMDA VERÝ KESÝMÝNÝN KOD KESÝMÝNDEN SONRA YERLEÞTÝRÝLDÝÐÝ MODEL KULLANILMISTIR.

MYS SEGMENT PARA 'KOD '
ORG 100H
ASSUME CS:MYS,DS:MYS,SS:MYS

KAYNAK_BUL PROC NEAR
XOR BX,BX				;//KUYRUK DÝZÝSÝNÝN ÝNDÝSÝ OLARAK KULLANILACAK BX YAZMACI 0'LANIR.

MOV AL,K_ESIK			;//K_ESÝK DEGERÝ AL YAZMACINA KONUR.
MOV AH,B_ESIK			;//B_ESIK DEGERÝ AH YAZMACINA KONUR.
DON: CMP KUYRUK[BX],AL	;//KUYRUK DÝZÝSÝNÝN BX ÝNDÝSLÝ ELEMANI ÝLE AL KARÞILAÞTIRILIR.
JB SONRAKÝ				;//KUYRUK[BX],AL'DEN KUCUKSE SONRAKÝ ETÝKETÝNE ATLANIR.
CMP KUYRUK[BX],AH;		;//KUYRUK[BX],AL'DEN BUYUK ESÝTSE KUYRUK DÝZÝSÝNÝN BX ÝNDÝSLÝ ELEMANI ÝLE AH KARÞILASTIRILIR.
JBE BULUNDU				;//KUYRUK[BX],AH'DEN KUCUK ESÝTSE BULUNDU ETÝKETÝNE ATLANIR.

SONRAKÝ:INC BX			;//KUYRUK[BX],AH'DEN BUYUKSE BX YAZMACININ DEGERÝ 1 ARTTIRILIR.
JMP DON					;//CEVRÝM KOSULUNA GÝTMEK ÝÇÝN DON ETÝKETÝNE ATLANIR.
BULUNDU:MOV INDIS,BL	;//KUYRUGA SONRADAN GÝREN KÝÞÝNÝN SIRASI BL,ÝNDÝS DEGÝSKENÝ ÝÇERÝSÝNE ATILIR.

SON:RET
KAYNAK_BUL ENDP
KUYRUK	DB 14,11,54,62,11,3,8,63,81,5,16
K_ESIK DB 15
B_ESÝK DB 50
INDIS DB ?
MYS ENDS
END KAYNAK_BUL

