/* 
SIRALI DÝZÝDE ARAMA 
10 WORD ELEMANLI ÝÞARETLÝ SAYÝLARDAN OLUSAN SIRALI BÝR DÝZÝDE VERÝLEN X(WORD)SAYISININ HANGÝ ADRESTE OLDUGUNU BULAN COM TÝPÝ ASSEMBLY PROGRAMINI YAZALIM.
NOT:DÝZÝ SIRALI OLDUGU ÝÇÝN YARIYA BÖLME ÝLE ARANAN ELEMANIN EN AZ KARÞILAÞTIRMA ÝLE BULUNMASI SAÐLANACAK,X SAYÝSÝNÝN DÝZÝ ÝÇÝNDE OLMAMASI DURUMUNU GÖSTERMEK ÜZERE ADRES DEGERÝ OLARAK 0FFFFH KULLANILACAKTIR.

*/

//ÝKÝLÝ ARAMA(BÝNARY SEARCH)

MYSEG SEGMENT PARA 'CODE'
ORG 100H
ASSUME CS:MYSEG,SS:MYSEG,DS:MYSEG
BILGI:JMP MAIN
DIZI 	DW -21,-8,-3,-1,0,4,14,21,45,67
ELEMAN DW 10
SAYI DW 45
ADRES DW 0FFFFH

MAIN PROC NEAR 
XOR SI,SI
MOV DI,ELEMAN

SHL DI,1
SUB DI,2
MOV AX,SAYI
KONT:CMP SI,DI
JG SON
MOV BX,SI
ADD BX,DI

SHR BX,1
AND BX,0FEH
CMP AX,DIZI[BX]
JE BULDU
JG SAGDA
MOV DI,BX
SUB DI,2

JMP KONT
SAGDA:MOV SI,BX
ADD SI,2

JMP KONT
BULDU:MOV ADRES,BX
MOV SI,DI

ADD SI,2
JMP KONT
SON:RET
MAIN ENDP
MYSEG ENDS
END BILGI
