/*
DIZIDE DEGER ARAMA
300 ELEMANLI WORD TANIMLI BÝR DÝZÝ ÝÇERÝSÝNDE VERÝLEN BYTE TANIMLI BÝR DEGERÝN 
KAC KERE GECTÝGÝNÝ BULAN EXE TÝPÝ ASSEMBLY PROGRAMINI YAZALIM.
PROGRAM ORGANÝZASYONU GERÇEKLEÞTÝRÝLÝRKEN DÝZÝNÝN ADRESÝNÝ,ELEMAN SAYÝSÝNÝ VE ARANAN SAYIYI ANA YORDAMIN YIGINA ATMASI VE ARDINDAN SAY ÝSÝMLÝ YARDIMCI YORDAMI ÇAÐIRMASI SAÐLANMALIDIR.
YARDIMCI YORDAMIN ÝSE SONUCU AX YAZMACI ÜZERÝNDEN DÖNDÜRMESÝ BEKLENMEKTEDÝR.

*/

//MAIN YORDAM ÝÇERÝSÝNDE SAY HARÝCÝ YORDAMI ÇAÐIRILMIÞTIR.

EXTRN SAY:FAR
MYSS SEGMENT PARA STACK 'S'
DW 20 DUP(?)
MYSS ENDS

MYDS SEGMENT PARA 'DATA'
DIZI 	DW 12,12,12,12,12,12,13,14,15,16,17
N 		DW 11
ARANAN 	DB 12

SONUC 	DW ?
MYDS 	ENDS

MYCS SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:MYCS,DS:MYDS,SS:MYSS
MAIN PROC FAR
PUSH DS
XOR AX,AX
PUSH AX
MOV AX,MYDS
MOV DS,AX
XOR AX,AX		;//AH YAZMACININ 0'LAMASI ÝÇÝN AX
				;//YAZMACI SIFIRLANIR.ÇÜNKÜ XOR AX,AX KODUNUN PERFORMANSI XOR AH,AH KOMUTU PERFORMANSINDAN DAHA ÝYÝDÝR.
MOV AL,ARANAN	;//ARANAN DEGÝSKENÝN DEGERÝ AL YAZMACINA KONUR.
PUSH AX			;//AX YIGINA ATILIR.
LEA AX,DIZI		;//DÝZÝNÝN ADRESÝ AX YAZMACINA ALINIR.
PUSH AX			;//AX ÜZERÝNDEN DIZININ ADRESÝ YIGINA ATILIR.

PUSH N			;//DIZININ ELEMAN (N)YIGINA ATILIR.
CALL SAY		;//SAY YORDAMI CAÐIRILIR.
MOV SONUC,AX	;//SAY YORDAMINDAN AX ÜZERÝNDEN DONDURÜLEN DEGER SONUC DEGÝSKENÝNE YERLESTÝRÝLÝR.


RETF
MAIN ENDP
MYCS ENDS
END MAIN

//SAY HARÝCÝ YORDAMI ÝÇERÝSÝNDE SAYMA ÝÞLEMÝ GERÇEKLEÞTÝRÝLMEKTEDÝR.

PUBLÝC SAY
MYCS SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:MYCS
SAY PROC FAR
PUSH CX
PUSH DI
PUSH BP
MOV BP,SP


MOV CX,[BP+10]

MOV DI,[BP+12]
MOV BX,[BP+14]
XOR AX,AX
L1:CMP BX,[DI]

JNE ATLA

INC AX

ATLA: ADD DI,2

LOOP L1
POP BP
POP DI
POP CX
RETF 6
SAY ENDP
MYCS ENDS
END

