/*
ÖRNEK 10-2

ÖNCELÝKLE BYTE TÝPÝNDE ÝKÝ DEGERÝ BL VE BH YAZMACLARI UZERÝNDEN ALAN VE BUNLARIN TOPLAMINI HESAPLAYARAK
AX YAZMACI ÜZERÝNDEN DONDUREN TOPLAMA ÝSMÝNDE BÝR YORDAMIN VAR OLDUGUNU VARSAYARAK BU YORDAMDAN SERVÝS ALACAK OLAN PROGRAMI YAZALIM.

TOPLAMA ÝSMÝNDEKÝ YORDAMIN GÝRÝÞ PARAMETRELERÝ BYTE OLDUGU ÝÇÝN SAYI1 VE SAYI2 ÝSÝMLÝ DEGÝSKENLER BYTE,TOPLAM DEGERÝ AX YAZMACI ÜZERÝNDEN DONDUGU ÝÇÝN SONUC DEGERÝ WORD OLARAK VERÝ KESÝMÝNDE TANIMLANMALIDIR.

BU ÖRNEÐÝMÝZDE EXTRN KOMUTUNUN KULLANILMAMASI DURUMUNDA NE TÝP HATA MESAJLARI ÝLE KARÞILAÞILACAGINI ÝNCELEYCEGÝZ.

ALINAN HATA MESAJLARI DOGRULTUSUNDA KODUMUZA EXTRN TANIMINI ÝLAVE EDEREK HEMEN ARDINDAN TOPLAMA ÝSÝMLÝ YORDAMI BARINDIRAN KODU YAZICAGIZ.

SON OLARAK ÝKÝ FARKLI ASSEMBLY KAYNAK KODUNDAN NE ÞEKÝLDE ÇALIÞTIRILABÝLÝR BÝR NESNE KODU ÜRETÝLECEGÝNÝ GÖRECEGÝZ.

*/
//PROGRAM :ÖRNEK 10-2 ASM
//TOPLAMA ÝSÝMLÝ YARDIMCI YORDAMIN ÇAÐRILMASI

PAGE 60,80
TITLE YARDIMCI YORDAM ÇAÐIRMA
STSEG SEGMENT PARA STACK 'STACK'
	DW 12 DUP(0)
STSEG ENDS
DTSEG SEGMENT PARA 'DATA'	
//KULLANILACAK DEGÝSKENLER TANIMLANIR.
SAYI1 DB 12H
SAYI2 DW 78H
SONUC DW 0H
DTSEG ENDS
CDSEG SEGMENT PARA 'CODE'
	ASSUME CS:CDSEG,SS:STSEG,DS:DTSEG
BASLA PROC FAR

//DONUS ÝÇÝN GEREKLÝ OLAN DEGERLER YIGINDA SAKLANIYOR

PUSH DS
XOR AX,AX
PUSH AX
	
//DATASG ÝSMÝYLE TANIMLI KESÝM ALANINA ERÝÞEBÝLMEK ÝÇÝN GEREKLÝ TANIMLAR

MOV AX,DTSEG
MOV DS,AX

//ÝÞLEM BLOGU BASLIYOR

MOV BH,SAYI1	;//DEGERLER BH VE BL YAZMACLARI UZERÝNDEN 
MOV BL,SAYÝ2	;//CAÐRILACAK OLAN YARDIMCI YORDAMA AKTARILIR
CALL TOPLAMA 	;//YORDAM ÇAÐIRILIR
MOV SONUC,AX 	;//TOPLAMA ÝÞLEMÝNÝN SONUCUNU AX YAZMACINDA
RET
BASLA ENDP
CDSEG ENDS
END BASLA		;//PROGRAMIN BASLANGIC NOKTASI	







//PROGRAM :ÖRNEK 10-2-1 ASM
//TOPLAMA ÝSÝMLÝ YARDIMCI YORDAMIN ÝÇÝNDE BULUNDUGU PROGRAM

PAGE 60,80
TITLE YARDIMCI PROCEDURE ÇAÐIRMA
PUBLÝC TOPLAMA
CODES SEGMENT PARA 'CODE'
ASSUME CS:CODES
TOPLAMA PROC FAR

//ÝÞLEM BLOGU ÇALIÞIYOR.

XOR AX,AX	;//AX YAZMACINI SIFIRLA
ADD AL,BL	;//AL ÜZERÝNDE TOPLAMAYA BASLA
ADD AL,BH
ADC AH,0	;//CF OLUÞMASI DURUMUNDA BUNU AH'YA AKTAR
RET			;//CAÐRILDIGIN YERE DON
TOPLAMA ENDP
CODES ENDS
END
