CODESG  SEGMENT PARA 'CODE'
        ORG 100H
        ASSUME CS:CODESG, SS:CODESG, DS:CODESG, ES:CODESG
BILGI:  JMP BASLA
MESAJ DB 'Merhaba!', '$'


BASLA   PROC NEAR
	LEA DX, MESAJ
	MOV AH, 09H
	INT 21H
	
        RET
BASLA   ENDP
CODESG  ENDS
        END BILGI

